apiVersion: batch/v1
kind: Job
metadata:
  name: data-generator
  namespace: katagiri-liberty-test
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: data-generator
        image: image-registry.openshift-image-registry.svc:5000/katagiri-liberty-test/data-generator:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: db_host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
      restartPolicy: Never
  backoffLimit: 1
